### ISSUE TITLE
Very old games do not have an approval date

### ISSUE THREAD

**Issue by Alexejhero** [Pathoschild/FluentNexus#1]
Some very old games (example fallout 3 and fallout new vegas) were added on nexusmods prior to the system accepting new games, and they have an approval date of 0 (according to a nexusmods admin).

![](https://cdn.discordapp.com/attachments/573432087122542593/573435913846128641/unknown.png)

![](https://user-images.githubusercontent.com/32238504/57065997-bc073900-6cd3-11e9-8176-50b679ac06d4.png)

When checking if a game was approved using `<Game>.ApprovedDate.HasValue`, old games appear unapproved.

![](https://user-images.githubusercontent.com/32238504/57065878-70ed2600-6cd3-11e9-9c59-8158d2e21680.png)

Possible solution: Add an `IsApproved` `bool` property in the `Game` class or give the `ApprovedDate` property a value even if the API returned 0.

**Comment by Pathoschild** [comment]
Thanks! I added the `IsApproved` field in [FluentNexus 0.5](https://www.nuget.org/packages/Pathoschild.FluentNexus).

For reference, the API sets `approved_date` to 0 (not approved), 1 (approved before the date was tracked), or a Unix timestamp.
