### ISSUE TITLE
Endorsing a mod requires a version but API does not require it

### ISSUE THREAD

**Issue by Mgamerz** [Pathoschild/FluentNexus#2]
The nexusmods API documentation does not tell you what exactly you are actually supposed to put into the version attribute for endorsing a mod. Looking at web interface this is not very intuitive either as it is a yes/no to the whole file. Passing null or "" results in a "You must provide a version number", but their API documentation does not specify this is required.

Is this an issue in the library or their documentation?

**Comment by Pathoschild** [comment]
The field is required, they just didn't mark it as such in their [API documentation](https://app.swaggerhub.com/apis-docs/NexusMods/nexus-mods_public_api_params_in_form_data/1.0#/Mods/post_v1_games_game_domain_name_mods_id_endorse.json). You need to pass in the mod or file version you're endorsing. It's only used for tracking purposes though, the API accepts any valid version.

**Comment by Mgamerz** [comment]
Ah. I'll just pass 1.0 then.

**Comment by Pathoschild** [comment]
If you have the mod info (or have the spare rate limit room), you can pass in the mod version:
```cs
Mod mod = await nexus.Mods.GetMod("stardewvalley", 2400);
await nexus.Mods.Endorse("stardewvalley", mod.ModID, mod.Version);
```
Otherwise just passing in 1.0 should work fine.
