### ISSUE TITLE
The ParentCategory propertie is always set to null.

### ISSUE THREAD

**Issue by ghost** [Pathoschild/FluentNexus#3]
The ParentCategory propertie of a GameCategory is always set to null.

A clear example is game domain : "callofduty2"

JSON:
{
"category_id": 16,
"name": "Mods",
"parent_category": 1
},
{
"category_id": 17,
"name": "Mini-Mods",
"parent_category": 16
}

Returned GameCategory object:

![image](https://user-images.githubusercontent.com/26540950/74866355-0afd8800-5353-11ea-9799-94580aa57325.png)

Could it be that ParentCategory propertie is set always to 0 during deserializing json data for some reason and there for this method is setting it to null ?
```
private void NormaliseGameData(params Game[] games)
```

**Comment by Pathoschild** [comment]
Hi! Does this version fix it for you?
* [Pathoschild.FluentNexus.0.8.1-alpha.1.nupkg.zip](https://github.com/Pathoschild/FluentNexus/files/4228256/Pathoschild.FluentNexus.0.8.1-alpha.1.nupkg.zip)

**Comment by ghost** [comment]
Hi, Yes this looks fine. Thanks.
