### ISSUE TITLE
size in bytes not available in library

### ISSUE THREAD

**Issue by Mgamerz** [Pathoschild/FluentNexus#4]
I've been talking to nexusmods and there is a new property in the API, for size_in_bytes.

![image](https://user-images.githubusercontent.com/2738836/125124783-e1fba580-e0b5-11eb-9781-93b7e3ee3942.png)

This doesn't appear to be used by any mod manager's yet but it would be beneficial for mine since I use filesize for lookups for other information. Apparently this is null in some mods (somehow) but would be a nice addition to the file endpoint.

**Comment by Pathoschild** [comment]
Added and deployed in FluentNexus 1.0.3. Thanks for reporting it!
